# Generated by Django 3.0.4 on 2020-03-21 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackerdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation', models.CharField(max_length=120)),
                ('task', models.CharField(max_length=120)),
                ('stardate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(max_length=24)),
                ('blockers', models.CharField(max_length=120)),
                ('spoc', models.CharField(max_length=24)),
                ('finished', models.BooleanField(default='False')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
