# Generated by Django 3.0.4 on 2020-03-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200322_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdata',
            name='blockers',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='spoc',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='status',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
